spring:
  application:
    name: hello-spring-cloud-web-admin-feign

server:
  port: 8765

thymeleaf:
  cache: false
  mode: LEGACYHTML5
  encoding: UTF-8
  servlet:
    content-type: text/html

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
